[build]
  publish = "."
  command = "node build.js"

[dev]
  publish = "."
  port = 8888

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=60"